//package exception_discussion;
//
//public class Try_Catch_Finally {
//	public static void main(String[] args) {
//		try
//		{
//			String s=  null;
//			String s1 ="Abc";
//			boolean s2 = s.equals(s1);
//			System.out.println(s2);
//		}
//		catch(ArithmeticException e)
//		{
//			System.out.println("its Nullpointer exception value");
//		}
//		catch(NullPointerException e)
//		{
//			System.out.println("its Nullpointer exception value");
//		}
//		finally
//		{
//			System.out.println("finally is executing");
//		}
//	}
//	
//
//}
